<?php

// Include the Square Connect API resources
require_once './sq/connect-php-sdk-master/autoload.php';

$authzToken = "sandbox-sq0atb-GeLo_51M97p1zCSzlRHQKQ"; // put your sandbox token here
$locationId = "";                 // we'll set this programmatically

// Create and configure a new API client object
$defaultApiConfig = new \SquareConnect\Configuration();
$defaultApiConfig->setAccessToken($authzToken);
$defaultApiClient = new \SquareConnect\ApiClient($defaultApiConfig) ;

// Create a LocationsApi client to load the location ID
$locationsApi = new SquareConnect\Api\LocationsApi($defaultApiClient);



try {

 $apiResponse = $locationsApi->listLocations();

  foreach ($apiResponse->getLocations() as $location) {
    if (in_array('CREDIT_CARD_PROCESSING', $location->getCapabilities())) {
      $locationId = $location.getId();
    }
  }
  if ($locationId == null) {
    print("[ERROR] LOCATION ID NOT SET");
    throw new RuntimeException('No location ID found');
  }
} catch (\SquareConnect\ApiException $e) {
  // Display the exception details and forward the exception
  echo "The SquareConnect\Api\LocationApi object threw an exception.<br>" .
       "API call: LocationApi->listLocations" .
       "<pre>" . var_dump($e) . "</pre>";
  throw $e;
}



$buyerInfo = array();
$buyerInfo['buyer_email_address'] = "thebuyer@example.com";
$buyerInfo['shipping_address'] = array(
  'address_line_1' => "123 Main St",
  'locality' => "San Francisco",
  'administrative_district_level_1' => "CA",
  'postal_code' => "94114",
  'country' => "US"
);
$buyerInfo['billing_address'] = array(
  'address_line_1' => "500 Electric Ave",
  'address_line_2' => "Suite 600",
  'administrative_district_level_1' => "NY",
  'locality' => "New York",
  'postal_code' => "20003",
  'country' => "US"
);



// This is a sandbox nonce; replace this with a nonce generated by SqPaymentForm
$cardNonce = "fake-card-nonce-ok";

$idempotencyKey = uniqid();

$paymentInfo = array();
$paymentInfo['idempotency_key'] = $idempotencyKey;
$paymentInfo['amount_money'] = array('amount' => 1000, 'currency' => "USD");
$paymentInfo['card_nonce'] = $cardNonce;


$referenceInfo = array();
$referenceInfo['reference_id'] = 'Confirmation #12345';
$referenceInfo['note'] = 'A useful note about this transaction';




$txRequest = array_merge(
  $buyerInfo,
  $paymentInfo,
  $referenceInfo
);

$transactionsApi = new \SquareConnect\Api\TransactionsApi($defaultApiClient);

try {

  $apiResponse = $transactionsApi->charge($locationId, $txRequest);

  // For now, just print the result to the screen
  echo "<pre>" . print_r($apiResponse, true) . "</pre>";

} catch (\SquareConnect\ApiException $e) {
  echo "<hr>" .
       "The SquareConnect\Api\TransactionsApi object threw an exception.<br>" .
       "API call: <code>TransactionsApi->charge</code>" .
       "<pre>" . var_dump($e) . "</pre>";
  throw $e;
}

?>